# Generated by Django 5.1.1 on 2024-10-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_status',
            field=models.CharField(choices=[('s', 'Success'), ('p', 'Pending'), ('f', 'Failed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='interval',
            field=models.CharField(choices=[('m', 'Monthly'), ('y', 'yearly'), ('h', '6 Month'), ('s', '3 Month')], max_length=1),
        ),
    ]
