# Generated by Django 5.1.1 on 2024-10-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_status',
            field=models.CharField(choices=[('f', 'Failed'), ('p', 'Pending'), ('s', 'Success')], max_length=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='interval',
            field=models.CharField(choices=[('h', '6 Month'), ('m', 'Monthly'), ('s', '3 Month'), ('y', 'yearly')], max_length=1),
        ),
    ]
