# Generated by Django 5.1.1 on 2024-10-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_paymenthistory_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_status',
            field=models.CharField(choices=[('p', 'Pending'), ('s', 'Success'), ('f', 'Failed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='interval',
            field=models.CharField(choices=[('y', 'yearly'), ('m', 'Monthly'), ('h', '6 Month'), ('s', '3 Month')], max_length=1),
        ),
    ]
