# Generated by Django 5.1.1 on 2024-10-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_paymenthistory_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_status',
            field=models.CharField(choices=[('f', 'Failed'), ('s', 'Success'), ('p', 'Pending')], max_length=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='interval',
            field=models.CharField(choices=[('s', '3 Month'), ('m', 'Monthly'), ('h', '6 Month'), ('y', 'yearly')], max_length=1),
        ),
    ]
