# Generated by Django 5.1.1 on 2024-10-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_paymenthistory_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='interval',
            field=models.CharField(choices=[('m', 'Monthly'), ('y', 'yearly'), ('s', '3 Month'), ('h', '6 Month')], max_length=1),
        ),
    ]
