# Generated by Django 5.1.1 on 2024-10-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subscription_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_status',
            field=models.CharField(choices=[('p', 'Pending'), ('f', 'Failed'), ('s', 'Success')], max_length=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='interval',
            field=models.CharField(choices=[('s', '3 Month'), ('m', 'Monthly'), ('h', '6 Month'), ('y', 'yearly')], max_length=1),
        ),
    ]
