# Generated by Django 5.1.1 on 2024-10-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (5, '5'), (4, '4'), (3, '3'), (2, '2')]),
        ),
    ]
