# Generated by Django 5.1.1 on 2024-10-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (4, '4'), (3, '3'), (2, '2'), (5, '5')]),
        ),
    ]
