# Generated by Django 5.1.1 on 2024-10-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(3, '3'), (5, '5'), (4, '4'), (2, '2'), (1, '1')]),
        ),
    ]
