# Generated by Django 5.1.1 on 2024-10-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='detail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (1, '1')]),
        ),
    ]
