# Generated by Django 5.1.1 on 2024-10-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0005_genres_detail_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='biography',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')]),
        ),
    ]
