# Generated by Django 5.1.1 on 2024-10-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0006_alter_cast_biography_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(2, '2'), (5, '5'), (4, '4'), (3, '3'), (1, '1')]),
        ),
    ]
