# Generated by Django 5.1.1 on 2024-10-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0007_alter_movie_description_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (3, '3'), (5, '5'), (2, '2'), (4, '4')]),
        ),
    ]
